---

- name: Copy host resolver
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Install software-properties-common
  apt:
    update_cache: yes
    force_apt_get: yes
    pkg:
    - software-properties-common
    - curl
    - wget
    - nano
  
- name: Install Java
  apt:
    update_cache: yes
    force_apt_get: yes
    pkg:
    - openjdk-8-jdk

- name: create groud sdn
  group:
    name: sdn
    state: present

- name: create user sdn
  user:
    system: yes
    group: sdn
    name: sdn

- name: Upload onos-{{ onos_version }}.tar.gz
  copy:
    src: onos-{{ onos_version }}.tar.gz
    dest: "/tmp/onos-{{ onos_version }}.tar.gz"

- name: extract onos-{{ onos_version }}.tar.gz
  unarchive:
    src: /tmp/onos-{{ onos_version }}.tar.gz
    dest: /opt
    remote_src: yes
    owner: sdn
    group: sdn

- name: stat onos directory
  stat: 
    path: /opt/onos-{{ onos_version }}
  register: onos_stat

- name: Delete onos-{{ onos_version }} link
  file:
    state: absent
    path: /opt/onos

- name: link onos-{{ onos_version }} to onos
  file:
    state: link
    src: /opt/onos-{{ onos_version }}
    dest: /opt/onos
    owner: sdn
    group: sdn
  when: onos_stat.stat.exists

- name: Create onos configuration
  template:
    src: "options.j2"
    dest: "/opt/onos/options"

- name: create onos directory
  file:
    path: /opt/onos/config
    state: directory

- name: Create onos configuration
  template:
    src: "cluster.json.j2"
    dest: "/opt/onos/config/cluster.json"
  notify: restart onos

- name: chown onos directory
  file:
    path: /opt/onos-{{ onos_version }}
    owner: sdn
    group: sdn
  when: onos_stat.stat.exists

- name: copy files
  copy:
    remote_src: yes
    src: /opt/onos/init/onos.initd
    dest: /etc/init.d/onos
    mode: 755
  notify: restart onos

- name: copy files
  copy:
    remote_src: yes
    src: /opt/onos/init/onos.service
    dest: /etc/systemd/system/
    mode: 755
  notify: restart onos