---

- name: Copy host resolver
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: Install software-properties-common
  apt:
    force_apt_get: yes
    update_cache: yes
    pkg:
    - software-properties-common
    - curl
    - wget
    - nano

- name: Install Java
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - openjdk-8-jdk

- name: create atomix directory
  file:
    path: /opt/atomix
    state: directory

- name: Upload atomix-dist-{{ atomix_version }}.tar.gz
  copy:
    src: "atomix-dist-{{ atomix_version }}.tar.gz"
    dest: "/tmp/atomix-dist-{{ atomix_version }}.tar.gz"

- name: extract atomix-dist-{{ atomix_version }}.tar.gz
  unarchive:
    src: "/tmp/atomix-dist-{{ atomix_version }}.tar.gz"
    dest: /opt/atomix
    remote_src: yes

- name: Create atomix configuration
  template:
    src: "atomix.conf.j2"
    dest: "/opt/atomix/conf/atomix.conf"
  notify: restart atomix

- name: Create atomix service files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 644
  with_items:
    - { src: 'atomix.service.j2', dest: '/etc/systemd/system/atomix.service' }
  notify: restart atomix